//<![CDATA[
(function(e){function m(a){e.fn.cycle.debug&&n(a)}function n(){window.console&&window.console.log&&window.console.log("[cycle] "+Array.prototype.join.call(arguments," "))}function A(a,b,d){function g(a,b,d){if(!a&&!0===b){a=e(d).data("cycle.opts");if(!a)return n("options not found, can not resume"),!1;d.cycleTimeout&&(clearTimeout(d.cycleTimeout),d.cycleTimeout=0);q(a.elements,a,1,!a.backwards)}}void 0==a.cycleStop&&(a.cycleStop=0);if(void 0===b||null===b)b={};if(b.constructor==String)switch(b){case "destroy":case "stop":d=
e(a).data("cycle.opts");if(!d)return!1;a.cycleStop++;a.cycleTimeout&&clearTimeout(a.cycleTimeout);a.cycleTimeout=0;e(a).removeData("cycle.opts");"destroy"==b&&B(d);return!1;case "toggle":return a.cyclePause=1===a.cyclePause?0:1,g(a.cyclePause,d,a),!1;case "pause":return a.cyclePause=1,!1;case "resume":return a.cyclePause=0,g(!1,d,a),!1;case "prev":case "next":d=e(a).data("cycle.opts");if(!d)return n('options not found, "prev/next" ignored'),!1;e.fn.cycle[b](d);return!1;default:b={fx:b}}else if(b.constructor==
Number){var f=b;b=e(a).data("cycle.opts");if(!b)return n("options not found, can not advance slide"),!1;if(0>f||f>=b.elements.length)return n("invalid slide index: "+f),!1;b.nextSlide=f;a.cycleTimeout&&(clearTimeout(a.cycleTimeout),a.cycleTimeout=0);"string"==typeof d&&(b.oneTimeFx=d);q(b.elements,b,1,f>=b.currSlide);return!1}return b}function y(a,b){if(!e.support.opacity&&b.cleartype&&a.style.filter)try{a.style.removeAttribute("filter")}catch(d){}}function B(a){a.next&&e(a.next).unbind(a.prevNextEvent);
a.prev&&e(a.prev).unbind(a.prevNextEvent);(a.pager||a.pagerAnchorBuilder)&&e.each(a.pagerAnchors||[],function(){this.unbind().remove()});a.pagerAnchors=null;a.destroy&&a.destroy(a)}function C(a,b,d,g,f){var c=e.extend({},e.fn.cycle.defaults,g||{},e.metadata?a.metadata():e.meta?a.data():{});c.autostop&&(c.countdown=c.autostopCount||d.length);var h=a[0];a.data("cycle.opts",c);c.$cont=a;c.stopCount=h.cycleStop;c.elements=d;c.before=c.before?[c.before]:[];c.after=c.after?[c.after]:[];c.after.unshift(function(){c.busy=
0});!e.support.opacity&&c.cleartype&&c.after.push(function(){y(this,c)});c.continuous&&c.after.push(function(){q(d,c,0,!c.backwards)});D(c);e.support.opacity||!c.cleartype||c.cleartypeNoBg||z(b);"static"==a.css("position")&&a.css("position","relative");c.width&&a.width(c.width);c.height&&"auto"!=c.height&&a.height(c.height);c.startingSlide?c.startingSlide=parseInt(c.startingSlide):c.backwards&&(c.startingSlide=d.length-1);if(c.random){c.randomMap=[];for(h=0;h<d.length;h++)c.randomMap.push(h);c.randomMap.sort(function(a,
b){return Math.random()-.5});c.randomIndex=1;c.startingSlide=c.randomMap[1]}else c.startingSlide>=d.length&&(c.startingSlide=0);c.currSlide=c.startingSlide||0;var k=c.startingSlide;b.css({position:"absolute",top:0,left:0}).hide().each(function(a){a=c.backwards?k?a<=k?d.length+(a-k):k-a:d.length-a:k?a>=k?d.length-(a-k):k-a:d.length-a;e(this).css("z-index",a)});e(d[k]).css("opacity",1).show();y(d[k],c);c.fit&&c.width&&b.width(c.width);c.fit&&c.height&&"auto"!=c.height&&b.height(c.height);if(c.containerResize&&
!a.innerHeight()){for(var l=h=0,x=0;x<d.length;x++){var r=e(d[x]),m=r[0],u=r.outerWidth(),v=r.outerHeight();u||(u=m.offsetWidth||m.width||r.attr("width"));v||(v=m.offsetHeight||m.height||r.attr("height"));h=u>h?u:h;l=v>l?v:l}0<h&&0<l&&a.css({width:h+"px",height:l+"px"})}c.pause&&a.hover(function(){this.cyclePause++},function(){this.cyclePause--});if(!1===E(c))return!1;var t=!1;g.requeueAttempts=g.requeueAttempts||0;b.each(function(){var a=e(this);this.cycleH=c.fit&&c.height?c.height:a.height()||this.offsetHeight||
this.height||a.attr("height")||0;this.cycleW=c.fit&&c.width?c.width:a.width()||this.offsetWidth||this.width||a.attr("width")||0;if(a.is("img")){var a=e.browser.mozilla&&34==this.cycleW&&19==this.cycleH&&!this.complete,b=e.browser.opera&&(42==this.cycleW&&19==this.cycleH||37==this.cycleW&&17==this.cycleH)&&!this.complete,d=0==this.cycleH&&0==this.cycleW&&!this.complete;if(e.browser.msie&&28==this.cycleW&&30==this.cycleH&&!this.complete||a||b||d){if(f.s&&c.requeueOnImageNotLoaded&&100>++g.requeueAttempts)return n(g.requeueAttempts,
" - img slide not loaded, requeuing slideshow: ",this.src,this.cycleW,this.cycleH),setTimeout(function(){e(f.s,f.c).cycle(g)},c.requeueTimeout),t=!0,!1;n("could not determine size of image: "+this.src,this.cycleW,this.cycleH)}}return!0});if(t)return!1;c.cssBefore=c.cssBefore||{};c.animIn=c.animIn||{};c.animOut=c.animOut||{};b.not(":eq("+k+")").css(c.cssBefore);c.cssFirst&&e(b[k]).css(c.cssFirst);if(c.timeout)for(c.timeout=parseInt(c.timeout),c.speed.constructor==String&&(c.speed=e.fx.speeds[c.speed]||
parseInt(c.speed)),c.sync||(c.speed/=2),h="shuffle"==c.fx?500:250;c.timeout-c.speed<h;)c.timeout+=c.speed;c.easing&&(c.easeIn=c.easeOut=c.easing);c.speedIn||(c.speedIn=c.speed);c.speedOut||(c.speedOut=c.speed);c.slideCount=d.length;c.currSlide=c.lastSlide=k;c.random?(++c.randomIndex==d.length&&(c.randomIndex=0),c.nextSlide=c.randomMap[c.randomIndex]):c.nextSlide=c.backwards?0==c.startingSlide?d.length-1:c.startingSlide-1:c.startingSlide>=d.length-1?0:c.startingSlide+1;if(!c.multiFx)if(h=e.fn.cycle.transitions[c.fx],
e.isFunction(h))h(a,b,c);else if("custom"!=c.fx&&!c.multiFx)return n("unknown transition: "+c.fx,"; slideshow terminating"),!1;a=b[k];c.before.length&&c.before[0].apply(a,[a,a,c,!0]);1<c.after.length&&c.after[1].apply(a,[a,a,c,!0]);c.next&&e(c.next).bind(c.prevNextEvent,function(){return w(c,1)});c.prev&&e(c.prev).bind(c.prevNextEvent,function(){return w(c,0)});(c.pager||c.pagerAnchorBuilder)&&F(d,c);G(c,d);return c}function D(a){a.original={before:[],after:[]};a.original.cssBefore=e.extend({},a.cssBefore);
a.original.cssAfter=e.extend({},a.cssAfter);a.original.animIn=e.extend({},a.animIn);a.original.animOut=e.extend({},a.animOut);e.each(a.before,function(){a.original.before.push(this)});e.each(a.after,function(){a.original.after.push(this)})}function E(a){var b,d=e.fn.cycle.transitions;if(0<a.fx.indexOf(",")){a.multiFx=!0;a.fxs=a.fx.replace(/\s*/g,"").split(",");for(b=0;b<a.fxs.length;b++){var g=a.fxs[b];var f=d[g];f&&d.hasOwnProperty(g)&&e.isFunction(f)||(n("discarding unknown transition: ",g),a.fxs.splice(b,
1),b--)}if(!a.fxs.length)return n("No valid transitions named; slideshow terminating."),!1}else if("all"==a.fx)for(p in a.multiFx=!0,a.fxs=[],d)f=d[p],d.hasOwnProperty(p)&&e.isFunction(f)&&a.fxs.push(p);if(a.multiFx&&a.randomizeEffects){f=Math.floor(20*Math.random())+30;for(b=0;b<f;b++)a.fxs.push(a.fxs.splice(Math.floor(Math.random()*a.fxs.length),1)[0]);m("randomized fx sequence: ",a.fxs)}return!0}function G(a,b){a.addSlide=function(d,g){var f=e(d),c=f[0];a.autostopCount||a.countdown++;b[g?"unshift":
"push"](c);if(a.els)a.els[g?"unshift":"push"](c);a.slideCount=b.length;f.css("position","absolute");f[g?"prependTo":"appendTo"](a.$cont);g&&(a.currSlide++,a.nextSlide++);e.support.opacity||!a.cleartype||a.cleartypeNoBg||z(f);a.fit&&a.width&&f.width(a.width);a.fit&&a.height&&"auto"!=a.height&&f.height(a.height);c.cycleH=a.fit&&a.height?a.height:f.height();c.cycleW=a.fit&&a.width?a.width:f.width();f.css(a.cssBefore);(a.pager||a.pagerAnchorBuilder)&&e.fn.cycle.createPagerAnchor(b.length-1,c,e(a.pager),
b,a);if(e.isFunction(a.onAddSlide))a.onAddSlide(f);else f.hide()}}function q(a,b,d,g){d&&b.busy&&b.manualTrump&&(m("manualTrump in go(), stopping active transition"),e(a).stop(!0,!0),b.busy=!1);if(b.busy)m("transition active, ignoring new tx request");else{var f=b.$cont[0],c=a[b.currSlide],h=a[b.nextSlide];if(f.cycleStop==b.stopCount&&(0!==f.cycleTimeout||d))if(d||f.cyclePause||b.bounce||!(b.autostop&&0>=--b.countdown||b.nowrap&&!b.random&&b.nextSlide<b.currSlide)){var k=!1;if((d||!f.cyclePause)&&
b.nextSlide!=b.currSlide){var k=!0,l=b.fx;c.cycleH=c.cycleH||e(c).height();c.cycleW=c.cycleW||e(c).width();h.cycleH=h.cycleH||e(h).height();h.cycleW=h.cycleW||e(h).width();if(b.multiFx){if(void 0==b.lastFx||++b.lastFx>=b.fxs.length)b.lastFx=0;l=b.fxs[b.lastFx];b.currFx=l}b.oneTimeFx&&(l=b.oneTimeFx,b.oneTimeFx=null);e.fn.cycle.resetState(b,l);b.before.length&&e.each(b.before,function(a,d){f.cycleStop==b.stopCount&&d.apply(h,[c,h,b,g])});l=function(){e.each(b.after,function(a,d){f.cycleStop==b.stopCount&&
d.apply(h,[c,h,b,g])})};m("tx firing; currSlide: "+b.currSlide+"; nextSlide: "+b.nextSlide);b.busy=1;if(b.fxFn)b.fxFn(c,h,b,l,g,d&&b.fastOnEvent);else if(e.isFunction(e.fn.cycle[b.fx]))e.fn.cycle[b.fx](c,h,b,l,g,d&&b.fastOnEvent);else e.fn.cycle.custom(c,h,b,l,g,d&&b.fastOnEvent)}if(k||b.nextSlide==b.currSlide)b.lastSlide=b.currSlide,b.random?(b.currSlide=b.nextSlide,++b.randomIndex==a.length&&(b.randomIndex=0),b.nextSlide=b.randomMap[b.randomIndex],b.nextSlide==b.currSlide&&(b.nextSlide=b.currSlide==
b.slideCount-1?0:b.currSlide+1)):b.backwards?(d=0>b.nextSlide-1)&&b.bounce?(b.backwards=!b.backwards,b.nextSlide=1,b.currSlide=0):(b.nextSlide=d?a.length-1:b.nextSlide-1,b.currSlide=d?0:b.nextSlide+1):(d=b.nextSlide+1==a.length)&&b.bounce?(b.backwards=!b.backwards,b.nextSlide=a.length-2,b.currSlide=a.length-1):(b.nextSlide=d?0:b.nextSlide+1,b.currSlide=d?a.length-1:b.nextSlide-1);k&&b.pager&&b.updateActivePagerLink(b.pager,b.currSlide,b.activePagerClass);k=0;b.timeout&&!b.continuous?k=t(a[b.currSlide],
a[b.nextSlide],b,g):b.continuous&&f.cyclePause&&(k=10);0<k&&(f.cycleTimeout=setTimeout(function(){q(a,b,0,!b.backwards)},k))}else b.end&&b.end(b)}}function t(a,b,d,e){if(d.timeoutFn){for(a=d.timeoutFn.call(a,a,b,d,e);250>a-d.speed;)a+=d.speed;m("calculated timeout: "+a+"; speed: "+d.speed);if(!1!==a)return a}return d.timeout}function w(a,b){var d=b?1:-1,g=a.elements,f=a.$cont[0],c=f.cycleTimeout;c&&(clearTimeout(c),f.cycleTimeout=0);if(a.random&&0>d)a.randomIndex--,-2==--a.randomIndex?a.randomIndex=
g.length-2:-1==a.randomIndex&&(a.randomIndex=g.length-1),a.nextSlide=a.randomMap[a.randomIndex];else if(a.random)a.nextSlide=a.randomMap[a.randomIndex];else if(a.nextSlide=a.currSlide+d,0>a.nextSlide){if(a.nowrap)return!1;a.nextSlide=g.length-1}else if(a.nextSlide>=g.length){if(a.nowrap)return!1;a.nextSlide=0}f=a.onPrevNextEvent||a.prevNextClick;e.isFunction(f)&&f(0<d,a.nextSlide,g[a.nextSlide]);q(g,a,1,b);return!1}function F(a,b){var d=e(b.pager);e.each(a,function(g,f){e.fn.cycle.createPagerAnchor(g,
f,d,a,b)});b.updateActivePagerLink(b.pager,b.startingSlide,b.activePagerClass)}function z(a){function b(a){a=parseInt(a).toString(16);return 2>a.length?"0"+a:a}function d(a){for(;a&&"html"!=a.nodeName.toLowerCase();a=a.parentNode){var d=e.css(a,"background-color");if(0<=d.indexOf("rgb"))return a=d.match(/\d+/g),"#"+b(a[0])+b(a[1])+b(a[2]);if(d&&"transparent"!=d)return d}return"#ffffff"}m("applying clearType background-color hack");a.each(function(){e(this).css("background-color",d(this))})}void 0==
e.support&&(e.support={opacity:!e.browser.msie});e.fn.cycle=function(a,b){var d={s:this.selector,c:this.context};if(0===this.length&&"stop"!=a){if(!e.isReady&&d.s)return n("DOM not ready, queuing slideshow"),e(function(){e(d.s,d.c).cycle(a,b)}),this;n("terminating; zero elements found by selector"+(e.isReady?"":" (DOM not ready)"));return this}return this.each(function(){var g=A(this,a,b);if(!1!==g){g.updateActivePagerLink=g.updateActivePagerLink||e.fn.cycle.updateActivePagerLink;this.cycleTimeout&&
clearTimeout(this.cycleTimeout);this.cycleTimeout=this.cyclePause=0;var f=e(this),c=g.slideExpr?e(g.slideExpr,this):f.children(),h=c.get();if(2>h.length)n("terminating; too few slides: "+h.length);else{var k=C(f,c,h,g,d);!1!==k&&(f=k.continuous?10:t(h[k.currSlide],h[k.nextSlide],k,!k.backwards))&&(f+=k.delay||0,10>f&&(f=10),m("first timeout: "+f),this.cycleTimeout=setTimeout(function(){q(h,k,0,!g.backwards)},f))}}})};e.fn.cycle.resetState=function(a,b){b=b||a.fx;a.before=[];a.after=[];a.cssBefore=
e.extend({},a.original.cssBefore);a.cssAfter=e.extend({},a.original.cssAfter);a.animIn=e.extend({},a.original.animIn);a.animOut=e.extend({},a.original.animOut);a.fxFn=null;e.each(a.original.before,function(){a.before.push(this)});e.each(a.original.after,function(){a.after.push(this)});var d=e.fn.cycle.transitions[b];e.isFunction(d)&&d(a.$cont,e(a.elements),a)};e.fn.cycle.updateActivePagerLink=function(a,b,d){e(a).each(function(){e(this).children().removeClass(d).eq(b).addClass(d)})};e.fn.cycle.next=
function(a){w(a,1)};e.fn.cycle.prev=function(a){w(a,0)};e.fn.cycle.createPagerAnchor=function(a,b,d,g,f){e.isFunction(f.pagerAnchorBuilder)?(b=f.pagerAnchorBuilder(a,b),m("pagerAnchorBuilder("+a+", el) returned: "+b)):b='<a href="#">'+(a+1)+"</a>";if(b){var c=e(b);if(0===c.parents("body").length){var h=[];1<d.length?(d.each(function(){var a=c.clone(!0);e(this).append(a);h.push(a[0])}),c=e(h)):c.appendTo(d)}f.pagerAnchors=f.pagerAnchors||[];f.pagerAnchors.push(c);c.bind(f.pagerEvent,function(b){b.preventDefault();
f.nextSlide=a;b=f.$cont[0];var c=b.cycleTimeout;c&&(clearTimeout(c),b.cycleTimeout=0);b=f.onPagerEvent||f.pagerClick;e.isFunction(b)&&b(f.nextSlide,g[f.nextSlide]);q(g,f,1,f.currSlide<a)});/^click/.test(f.pagerEvent)||f.allowPagerClickBubble||c.bind("click.cycle",function(){return!1});f.pauseOnPagerHover&&c.hover(function(){f.$cont[0].cyclePause++},function(){f.$cont[0].cyclePause--})}};e.fn.cycle.hopsFromLast=function(a,b){var d=a.lastSlide,e=a.currSlide;return b?e>d?e-d:a.slideCount-d:e<d?d-e:d+
a.slideCount-e};e.fn.cycle.commonReset=function(a,b,d,g,f,c){e(d.elements).not(a).hide();d.cssBefore.opacity=1;d.cssBefore.display="block";d.slideResize&&!1!==g&&0<b.cycleW&&(d.cssBefore.width=b.cycleW);d.slideResize&&!1!==f&&0<b.cycleH&&(d.cssBefore.height=b.cycleH);d.cssAfter=d.cssAfter||{};d.cssAfter.display="none";e(a).css("zIndex",d.slideCount+(!0===c?1:0));e(b).css("zIndex",d.slideCount+(!0===c?0:1))};e.fn.cycle.custom=function(a,b,d,g,f,c){var h=e(a),k=e(b),l=d.speedIn;a=d.speedOut;var m=d.easeIn;
b=d.easeOut;k.css(d.cssBefore);c&&(l="number"==typeof c?a=c:a=1,m=b=null);h.animate(d.animOut,a,b,function(){d.cssAfter&&h.css(d.cssAfter);d.sync||k.animate(d.animIn,l,m,g)});d.sync&&k.animate(d.animIn,l,m,g)};e.fn.cycle.transitions={fade:function(a,b,d){b.not(":eq("+d.currSlide+")").css("opacity",0);d.before.push(function(a,b,c){e.fn.cycle.commonReset(a,b,c);c.cssBefore.opacity=0});d.animIn={opacity:1};d.animOut={opacity:0};d.cssBefore={top:0,left:0}}};e.fn.cycle.ver=function(){return"2.94"};e.fn.cycle.defaults=
{fx:"fade",timeout:4E3,timeoutFn:null,continuous:0,speed:1E3,speedIn:null,speedOut:null,next:null,prev:null,onPrevNextEvent:null,prevNextEvent:"click.cycle",pager:null,onPagerEvent:null,pagerEvent:"click.cycle",allowPagerClickBubble:!1,pagerAnchorBuilder:null,before:null,after:null,end:null,easing:null,easeIn:null,easeOut:null,shuffle:null,animIn:null,animOut:null,cssBefore:null,cssAfter:null,fxFn:null,height:"auto",startingSlide:0,sync:1,random:0,fit:0,containerResize:1,slideResize:1,pause:0,pauseOnPagerHover:0,
autostop:0,autostopCount:0,delay:0,slideExpr:null,cleartype:!e.support.opacity,cleartypeNoBg:!1,nowrap:0,fastOnEvent:0,randomizeEffects:1,rev:0,manualTrump:!0,requeueOnImageNotLoaded:!0,requeueTimeout:250,activePagerClass:"activeSlide",updateActivePagerLink:null,backwards:!1}})(jQuery);
//]]>
